blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path('', views.index_view, name="index"),
    path('new_post/', views.new_post_view, name='new_post'),
    path('list/', views.PostListView.as_view(), name='list'),
    path('list/<int:pk>/', views.PostDetailView.as_view(), name='read_post'),
    path('create/', views.PostCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.PostUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.PostDeleteView.as_view(), name='delete'),
]

blog_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.urls import reverse

# Class of posts in the blog
class Post(models.Model):
    #very much self-explanatory variable names
    author = models.CharField(max_length=16)
    title = models.CharField(max_length=32)
    text = models.TextField()

    #string representation of class object
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:read_post',kwargs={'pk':self.pk})

# Comments, anyone can add. No veification
class Comment(models.Model):
    #very much self-explanatory variable names
    author = models.CharField(max_length=16)
    text = models.TextField()
    post_id = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments') #to which post is the comment

    #string representation of class object
    def __str__(self):
        return self.author

blog/forms.py
from django import forms
from .models import Comment, Post

class PostForm(forms.ModelForm):
    class Meta():
        model = Post
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        fields = 'author', 'text'

blog/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import PostForm
from .models import Comment, Post
from . import models
from django.urls import reverse_lazy

# Create your views here.
def index_view(request):
    maja_lista = Post.objects.order_by('title')[:5]
    posteku = {'post_list':maja_lista}
    return render(request, "blog/welcome.html", context=posteku)

def new_post_view(request):
    my_form = PostForm()
    if request.method == 'POST':
        my_form = PostForm(request.POST)
        if my_form.is_valid():
            my_form.save(commit=True)
            return render(request, "blog/create_post.html")
        else:
            print('ERORR')

    return render(request, "blog/create_post.html", {'my_form':my_form})

class PostListView(ListView):
    context_object_name = 'posts'
    model = models.Post

class PostDetailView(DetailView):
    #school to jest context
    model = models.Post
    template_name = 'blog/post_site.html'

class PostCreateView(CreateView):
    fields = '__all__'
    model = models.Post

class PostUpdateView(UpdateView):
    fields = ('title', 'text')
    model = models.Post

class PostDeleteView(DeleteView):
    model = models.Post
    success_url = reverse_lazy('blog:list')

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Blog project</title>
  </head>
  <body>
    <h1>Welcome to Blog</h1>
    {% block pojemnik %}{% endblock %}
  </body>
</html>

templates/blog/create_post.html
{% extends 'blog/base.html' %}
{% block pojemnik %}
  <div class="container">
    <div class="jumbotron">
      <form method="post">
        {{ my_form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="submit">
      </form>
    </div>
  </div>
{% endblock %}

templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{%block pojemnik%}
<h1>Delete {{post.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <input type="submit" value="DELETE">
  <a href="{% url 'blog:read_post' pk=post.pk %}">Cancel</a>
</form>
{%endblock%}

templates/blog/post_form.html
{% extends 'blog/base.html' %}
{%block pojemnik%}
<h1>
  {% if not form.instance.pk %}
  Create Post
  {% else %}
  Update Post
  {% endif %}
</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit">
</form>

{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}
{%block pojemnik%}
<h1>List:</h1>
<ol>
  {% for entry in posts %}
    <h2><li><a href="{{ entry.id }}">{{ entry.title }}</a></li></h2>
  {% endfor %}
</ol>
{%endblock%}

templates/blog/post_site.html
{% extends 'blog/base.html' %}
{% block pojemnik %}
  <h1>Post view page</h1>
  <div class="container">
    <div class="jumbotron">
      <h2>{{ post.title }}</h2>
      <p>{{ post.text }}</p>
      <p><i>{{ post.author }}</i></p>
    </div>

    <h2>Comments: </h2>
    {% for coms in  post.comments.all %}
      <div class="jumbotron">
        <p>{{ coms.text }}</p>
        <p><i>{{ coms.author }}</i></p>
      </div>
    {% endfor %}

    <a class = 'btn btn-primary' href="{% url 'blog:update' pk=post.pk %}">Update</a>
    <a href="{% url 'blog:delete' pk=post.pk %}">Delete</a>


  </div>
{% endblock %}

templates/blog/welcome.html
{% extends 'blog/base.html' %}
{% block pojemnik %}
  <a href="{% url 'blog:new_post' %}">Create new post</a>

  {% if post_list %}
    <div class="container">
      {% for entry in post_list %}
        <p><a href="{{ entry.id }}">{{ entry.title }}</a></p>
        <p><i>{{ entry.author }}</i></p>
      {% endfor %}
    </div>
  {% else %}
    <p>Nothing to declare / Nic do oclenia.</p>
  {% endif %}
{% endblock %}